[package]
name = "tinox"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
tinox_lexer = { package = "tinox-lexer", path = "../tinox-lexer" }
tinox_parser = { package = "tinox-parser", path = "../tinox-parser" }
tinox_codegen = { package = "tinox-codegen", path = "../tinox-codegen" }
tinox_typecheck = { package = "tinox-typecheck", path = "../tinox-typecheck" }
tinox_common = { package = "tinox-common", path = "../tinox-common" }
notify = "6"

[[bin]]
name = "tinox"
path = "src/main.rs"

[dev-dependencies]
tinox_lexer = { package = "tinox-lexer", path = "../tinox-lexer" }
tinox_parser = { package = "tinox-parser", path = "../tinox-parser" }
tinox_codegen = { package = "tinox-codegen", path = "../tinox-codegen" }
tinox_typecheck = { package = "tinox-typecheck", path = "../tinox-typecheck" }
