[package]
name = "tinox"
version.workspace = true
edition.workspace = true

[dependencies]
tinox_lexer = { package = "tinox-lexer", path = "../tinox-lexer" }
tinox_parser = { package = "tinox-parser", path = "../tinox-parser" }
tinox_codegen = { package = "tinox-codegen", path = "../tinox-codegen" }
tinox_typecheck = { package = "tinox-typecheck", path = "../tinox-typecheck" }
tinox_common = { package = "tinox-common", path = "../tinox-common" }
notify = "6"
serde = { workspace = true }
serde_yaml = { workspace = true }
ureq = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
zip = { workspace = true }
sha2 = { workspace = true }

[[bin]]
name = "tinox"
path = "src/main.rs"

[dev-dependencies]
tinox_lexer = { package = "tinox-lexer", path = "../tinox-lexer" }
tinox_parser = { package = "tinox-parser", path = "../tinox-parser" }
tinox_codegen = { package = "tinox-codegen", path = "../tinox-codegen" }
tinox_typecheck = { package = "tinox-typecheck", path = "../tinox-typecheck" }
